name: Daily News Briefing

on:
  schedule:
    # Runs every day at 08:00 Eastern (12:00 UTC)
    - cron: '03 9 * * *'
  workflow_dispatch:  # allows you to trigger it manually

jobs:
  briefing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Briefing
        env:
          GOOGLE_API_KEY:    ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_KEY:      ${{ secrets.NEWS_API_KEY }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_ADDRESS:     ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD:    ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python daily_briefing.py